# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUI_2(object):
    def setupUi(self, JarvisUI_2):
        JarvisUI_2.setObjectName("JarvisUI_2")
        JarvisUI_2.resize(879, 584)
        self.centralwidget = QtWidgets.QWidget(JarvisUI_2)
        self.centralwidget.setObjectName("centralwidget")
        self.JarvisUI = QtWidgets.QLabel(self.centralwidget)
        self.JarvisUI.setGeometry(QtCore.QRect(-20, -10, 901, 611))
        self.JarvisUI.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.JarvisUI.setText("")
        self.JarvisUI.setScaledContents(False)
        self.JarvisUI.setObjectName("JarvisUI")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 220, 221, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("3.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 10, 311, 311))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("1.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-50, 390, 261, 221))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("7.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(420, 290, 111, 121))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("5.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 390, 421, 211))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("4.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(580, -10, 351, 241))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("6.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 361, 191))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("8.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(666, 250, 201, 201))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("9.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(690, 480, 141, 31))
        self.pushButton.setStyleSheet("font: 75 12pt \"Orbitron\";\n"
"color: rgb(85, 85, 255);\n"
"background-color: rgb(148, 148, 148);\n"
"border : 1px solid white")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 520, 141, 31))
        self.pushButton_2.setStyleSheet("font: 75 12pt \"Orbitron\";\n"
"color: rgb(85, 85, 255);\n"
"background-color: rgb(148, 148, 148);\n"
"border : 1px solid white")
        self.pushButton_2.setObjectName("pushButton_2")
        JarvisUI_2.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUI_2)
        QtCore.QMetaObject.connectSlotsByName(JarvisUI_2)

    def retranslateUi(self, JarvisUI_2):
        _translate = QtCore.QCoreApplication.translate
        JarvisUI_2.setWindowTitle(_translate("JarvisUI_2", "MainWindow"))
        self.pushButton.setText(_translate("JarvisUI_2", "START JARVIS"))
        self.pushButton_2.setText(_translate("JarvisUI_2", "QUIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUI_2 = QtWidgets.QMainWindow()
    ui = Ui_JarvisUI_2()
    ui.setupUi(JarvisUI_2)
    JarvisUI_2.show()
    sys.exit(app.exec_())
